###
POST http://localhost:8082/students
Content-Type: application/json

{
  "id": 1,
  "name": "Nihat",
  "surname": "Huseynzade",
  "age": 19
}
###
POST http://localhost:8082/students
Content-Type: application/json

{
  "id": 2,
  "name": "Cavad",
  "surname": "Cavadov",
  "age": 21
}
###
GET http://localhost:8082/students
###
GET http://localhost:8082/students/2
###
PUT http://localhost:8082/students/2
Content-Type: application/json

{
  "name": "Huseyn",
  "surname": "Emiraslanov",
  "age": 21
}
###
DELETE http://localhost:8082/students/1
###